-- AlterTable
ALTER TABLE "Assessement" ALTER COLUMN "title" SET DATA TYPE VARCHAR(255);

-- AlterTable
ALTER TABLE "Chapter" ALTER COLUMN "title" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "titleGroup" SET DATA TYPE VARCHAR(255);

-- AlterTable
ALTER TABLE "Level" ALTER COLUMN "title" SET DATA TYPE VARCHAR(255);

-- AlterTable
ALTER TABLE "Subject" ALTER COLUMN "title" SET DATA TYPE VARCHAR(255);
